In [1]:
import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
# creating dataframe

df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
# preprocessing data
# handling null value
# taking median
import math

median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [5]:
# filling NA value

df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [6]:
# updating to original dataframe

df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
# creating linear regression object
model = linear_model.LinearRegression()

# training the model
# under square brakets are independent variables and rest one is dependent variable 

model.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [11]:
# three coefficeints
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [12]:
# intercept
model.intercept_

221323.00186540384

In [13]:
model.predict([[3000, 3, 40]])

array([498408.25158031])

In [14]:
model.predict([[2500, 4, 5]])

array([578876.03748933])